# Generated by Django 4.0.6 on 2022-07-30 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='用户名')),
                ('password', models.CharField(max_length=75, verbose_name='密码')),
            ],
            options={
                'verbose_name': '用户',
                'db_table': 'users',
            },
        ),
    ]
